Fe/bug fix
Studiofarma/Infolab pull request #107
Opened 2023-06-05 12:21 UTC by Luca071005

2023-06-05 13:47 UTC, paolo-venturi commented
Il progetto frontend ha uno standard relativo all'indentazione che viene mantenuta coerente grazie ad un'estensione.
L'ambiente di sviluppo va configurato seguendo le istruzioni qui riportate: https://github.com/Studiofarma/Infolab/issues/2
Una volta sistemato tutto fate ripassare tutti i file del frontend modificati.
In questo modo chi deve fare la review può vedere solo le modifiche effettive.

2023-06-06 07:43 UTC, lucapiccinelli commented on .configurations/InfolabApplication - with db.run.xml
> +    <option name="ALTERNATIVE_JRE_PATH" value="$PROJECT_DIR$/../../../../../Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot" />
E' tornata dentro questa modifica

2023-06-06 07:43 UTC, lucapiccinelli commented on .configurations/InfolabApplication - inmemory.run.xml
> +    <option name="ALTERNATIVE_JRE_PATH" value="$PROJECT_DIR$/../../../../../Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot" />
E' tornata dentro questa modifica

2023-06-06 07:43 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/service/ChatService.java
> +    public Timestamp saveMessageInDb(ChatMessageDto message, Username username, RoomName roomName){
Ci ho pensato. Sarebbe meglio far tornare tutta l'entinty `ChatMessageEntity` e non solo il timestamp, per consistenza della API

2023-06-06 07:53 UTC, ErPeddaro commented on .configurations/InfolabApplication - inmemory.run.xml
> +    <option name="ALTERNATIVE_JRE_PATH" value="$PROJECT_DIR$/../../../../../Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot" />
l'abbiamo fatto di proposito per non modificare ad ogni pull i config

2023-06-12 14:45 UTC, Luca071005 commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +            ${resolveMarkdown(
L'abbiamo fixata in un'altra brach prima che tu ce lo dicessi

2023-06-13 07:19 UTC, Luca071005 commented on src/main/java/com/cgm/infolab/service/ChatService.java
> +    public Timestamp saveMessageInDb(ChatMessageDto message, Username username, RoomName roomName){
Risolto anche questo

2023-06-13 07:35 UTC, paolo-venturi requested changes

2023-06-13 07:35 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +            style="${this.chat.unread > 0 ? "color:rgb(58 179 255)" : ""}"
io avrei condizionato la classe creando una classe apposita con il colore

2023-06-13 07:35 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +                    style="display:${this.notificationOpacity};"
Stesso discorso di sopra: classe condizionata e stile nella classe

2023-06-13 07:35 UTC, paolo-venturi commented on src/frontend/components/button-icon.js
> +      /* display: inline; */
commento da rimuovere

2023-06-13 07:35 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +      /* max-width: 200px;
commento da rimuovere

2023-06-13 08:49 UTC, Luca071005 commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +                    style="display:${this.notificationOpacity};"
non si può fare perchè nel css non possiamo usare le variabili js

2023-06-13 09:02 UTC, paolo-venturi approved these changes

2023-06-13 09:04 UTC, merged