Fe/search conversation
Studiofarma/Infolab pull request #108
Opened 2023-06-09 09:39 UTC by Luca071005

Implemented search chat and chat switching

2023-06-14 08:31 UTC, paolo-venturi requested changes

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/components/button-icon.js
> +      /* display: inline; */
commento tornato

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/components/input-field.js
> +	// setFocus() {
commenti da rimuovere

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +		activeChatName: { state: "general" },
"general" è una magic string

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +		// let timestamp = this.chat.lastMessage.timestamp
commento da rimuovere?

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +						style="${this.chat.unread > 0 ? "color:rgb(58 179 255)" : ""}"
è tornata la gerstione precedente

2023-06-14 08:31 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +		this.activeChatName = "general";
altra magic string

2023-06-14 09:02 UTC, Luca071005 commented on src/frontend/pages/chat/sidebar/conversation/conversation.js
> +						style="${this.chat.unread > 0 ? "color:rgb(58 179 255)" : ""}"
per adesso è hardcoded, sarà da implementare la funzionalità per far si che quella variabile diventi uguale al nome della prima chat nella lista all'avvio

2023-06-15 06:41 UTC, paolo-venturi requested changes
Mancano da sistemare:
1. elenco unico dei contatti 
2. barra di ricerca che si pulisce dopo aver selezionato un contatto
3. pulsante "X" per pulire il contenuto della barra di ricerca

2023-06-15 13:56 UTC, paolo-venturi commented
![Animation](https://github.com/Studiofarma/Infolab/assets/20678725/7f3a48b3-28ae-4870-ad2f-ed4f0a542d68)

Non ho errori in console o sulle chiamate, la chat tra user1 e user2 risulte sempre vuota []

2023-06-16 07:25 UTC, paolo-venturi approved these changes

2023-06-16 07:25 UTC, merged