Last download dates
Studiofarma/Infolab pull request #109
Opened 2023-06-13 13:52 UTC by McGyv246

Ho aggiunto un metodo che permette di contrassegnare tutti i messaggi non scaricati come scaricati.
Attualmente la cosa avviene tramite una query `INSERT SELECT`, la quale fa l'operazione basandosi sui contenuti del db.

Per ora il metodo viene chiamato nell'api get dei messaggi della room general.

NOTA: questa pull request causerebbe la rottura del db in caso lo si fosse già usato perché non potevo droppare il constraint di unicità, dato che non aveva nome.
Prima di mergiarla lo comunicherò agli altri.

2023-06-13 14:30 UTC, lucapiccinelli requested changes

2023-06-13 14:30 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/db/repository/DownloadDateRepository.java
> +    public void addWhereNotDownloadedYetForUser(UserEntity user, RoomEntity room) throws IllegalArgumentException {
che ne dici di `updateReadTimestamp` per il nome del metodo?

2023-06-13 14:30 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/controller/ChatApiMessagesController.java
> +        chatService.setAllMessagesAsDownloadedInRoom(
perchè non usi le entity dei messaggi che hai già in mano da `chatService.getAllMessagesGeneral` per sapere gli id dei messaggi di cui aggiornare il timestamp?

dovrebbe venire query più semplice

2023-06-16 09:09 UTC, McGyv246 commented
Il conflitto su `InfolabApplication -with db.run.xml` è perché non mi andava e ho cambiato il path. Però se lo mergiamo poi non va agli altri.

2023-06-16 15:24 UTC, lucapiccinelli requested changes

2023-06-16 15:24 UTC, lucapiccinelli commented on src/test/java/com/cgm/infolab/LastDownloadDateUpdateTests.java
> +    @Order(2)
Togli `@Order` se non necessario

2023-06-16 15:24 UTC, lucapiccinelli commented on src/test/java/com/cgm/infolab/LastDownloadDateUpdateTests.java
> +    @Order(1)
Togli `@Order` se non necessario

2023-06-19 13:56 UTC, lucapiccinelli approved these changes

2023-06-19 14:28 UTC, merged