Fe/refactor chat
Studiofarma/Infolab pull request #111
Opened 2023-06-14 13:55 UTC by ErPeddaro

refactored chat (ultimi 3 commit)

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +      </div>
Si dovrebbe creare un componente apposito per visualizzare e filtrare i profili da riutilizzare sia per la sidebar sia per i lmenù inoltra.

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +			this.forwardListVisibility ? "z-index: 500" : ""
Utilizzare la nuova feature per i modal: https://caniuse.com/dialog. Tramite questo elemento è possibile "stilare" il backdrop attraverso lo pseudoelemento ::backdrop e gestire la sua apertura dal punto di vista logico attraverso le funzioni JS dedicate.

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +        <p>Inoltra messaggio</p>
'inoltro dovrebbe consentire di selezionare più utenti

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +				<div class="message-settings">
Andrebbe creato un componente apposito MenuOptions, inoltre anche le per opzioni andrebbe fatto un componente OptionButton che eredita la classe del bottone di default

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +			top: 50%;
Andrebbe modificato lo spostamento del menù e il suo z-index.

2023-06-19 08:43 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +		}
Gestirei la cosa con javascript togliendo l'hover, in modo che cliccando sui tre punti si apra il menù.

2023-06-19 15:24 UTC, paolo-venturi commented on src/frontend/components/forward-list.js
> +      </div>
punto da valutare

2023-06-20 08:30 UTC, paolo-venturi commented on src/frontend/components/forward-list.js
> +      </div>
Creata issue https://github.com/Studiofarma/Infolab/issues/143

2023-06-20 09:09 UTC, Guidetti-Daniele commented on src/frontend/components/button-icon.js
> +			styleProp: "",
fatto

2023-06-20 09:09 UTC, Guidetti-Daniele commented on src/frontend/components/button-text.js
> +		styleProp: "",
fatto

2023-06-20 09:09 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +			this.forwardListVisibility ? "z-index: 500" : ""
fatto

2023-06-20 14:53 UTC, MalgarottiMirko commented on src/frontend/components/button-text.js
> +		return html` <button class="${this.toggleClass}">${this.text}</button> `;
Cambiare toggleClass da string a bool

2023-06-20 14:55 UTC, MalgarottiMirko commented on src/frontend/components/message-menu-option.js
> +    // da implementare
Non hai implementato il metodo handler

2023-06-20 14:58 UTC, MalgarottiMirko reviewed
Le options non si chiudono quando il cursore esce dalla zona

2023-06-20 14:59 UTC, MalgarottiMirko requested changes
sistemare i problemi elencati

2023-06-21 10:13 UTC, closed without merging