Fe/scroll to bottom arrow fix
Studiofarma/Infolab pull request #155
Opened 2023-06-20 14:21 UTC by Guidetti-Daniele

2023-06-20 14:49 UTC, DavideRichini commented
non visualizza i messaggi

2023-06-20 14:53 UTC, DavideRichini commented on src/frontend/pages/chat/input/insertion-bar.js
>      );
modifica non relativa alla PR

2023-06-21 06:53 UTC, DavideRichini commented on src/frontend/pages/chat/chat.js
> +						</ul>
rimossa la funzione di inoltro del messaggio

2023-06-21 06:58 UTC, DavideRichini commented on src/frontend/pages/chat/chat.js
> +			};
Rimosso codice non inerente alla PR. I messaggi non vengono più inviati

2023-06-21 08:13 UTC, MalgarottiMirko commented
Il forward dei messaggi non funziona

2023-06-21 08:17 UTC, MalgarottiMirko requested changes
Sistemari questi bug

2023-06-21 08:22 UTC, MalgarottiMirko approved these changes

2023-06-21 09:11 UTC, paolo-venturi approved these changes

2023-06-21 09:11 UTC, merged