Refactoring chat
Studiofarma/Infolab pull request #158
Opened 2023-06-21 08:52 UTC by Guidetti-Daniele

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +			<dialog @click=${(e) => this.closeForwardList(e,"")}>
Old: 
Utilizzare la nuova feature per i modal: https://caniuse.com/dialog. Tramite questo elemento è possibile "stilare" il backdrop attraverso lo pseudoelemento ::backdrop e gestire la sua apertura dal punto di vista logico attraverso le funzioni JS dedicate.

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +					</il-message-settings>
Old:
Andrebbe creato un componente apposito MenuOptions, inoltre anche le per opzioni andrebbe fatto un componente OptionButton che eredita la classe del bottone di default

New:

Creato componente per le impostazioni del messaggio

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message-settings.js
> +				</message-menu-option>
Old:
Andrebbe creato un componente apposito MenuOptions, inoltre anche le per opzioni andrebbe fatto un componente OptionButton che eredita la classe del bottone di default

New:
Creato componente per singola opzione

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +		}
Old:
Andrebbe modificato lo spostamento del menù e il suo z-index.

New: 

Fixato il posizionamento del menu settings

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message.js
> +	}
Old:
Gestirei la cosa con javascript togliendo l'hover, in modo che cliccando sui tre punti si apra il menù.

New:
L'apertura del menu-settings è regolata attraverso questa funzione

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message-settings.js
> +			<dialog @click=${this.closeDialog} @mouseleave=${this.closeDialog}>
Old:
Le options non si chiudono quando il cursore esce dalla zona

New:
La chiusura del menu settings è regolata dai 2 eventi

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/button-icon.js
>  	}
Old:
Questa proprietà non serve, potrebbe essere direttamente sostituita da una proprietà color da cui è possibile impostare un colore parametrico via css...

New:
La proprietà styleProp è stata sostituita da una per l'inserimento parametrico del colore.

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/button-text.js
> +		return html` <button class="${this.isActive ? "active" : ""}">${this.text}</button> `;
Old:
Stesso discorso fatto per le icone

New:
styleProp sostituito con questo boolean che verifica quando l'utente si trova nella scheda dell'editor e assegna al bottone la classe .active

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/components/message-menu-option.js
> +}
Old:
Non hai implementato il metodo handler

New:
Tolto il metodo handler, le funzioni vengono richiamate  esternamente dall'evento @click

2023-06-21 09:23 UTC, Guidetti-Daniele commented on src/frontend/pages/chat/chat.js
> +										.index=${index}
Passato index come attributo perchè serve alla funzione per cancellare il messaggio

2023-06-21 10:07 UTC, MalgarottiMirko commented
Old: Cambiare toggleClass da string a bool in "src/frontend/components/button-text.js"

2023-06-21 10:07 UTC, MalgarottiMirko commented
Old: Non hai implementato il metodo handler in "src/frontend/components/message-menu-option.js"

2023-06-21 10:08 UTC, MalgarottiMirko commented
Old: Le options non si chiudono quando il cursore esce dalla zona

2023-06-21 10:09 UTC, MalgarottiMirko requested changes
Old: sistemare i problemi elencati

2023-06-21 14:20 UTC, MalgarottiMirko commented on src/frontend/components/message-settings.js
> +	deleteMessage(message) {
Stai prendendo un parametro che non viene mai utilizzato

2023-06-21 14:23 UTC, MalgarottiMirko commented on src/frontend/pages/chat/input/editor/editor.js
rimuovi import inutilizzato

2023-06-21 15:02 UTC, MalgarottiMirko approved these changes

2023-06-22 06:46 UTC, paolo-venturi requested changes

2023-06-22 06:46 UTC, paolo-venturi commented on src/frontend/components/message.js
> +			return html`<div class="message-date">Today</div>`;
Ritronata scritta in inglese

2023-06-22 06:46 UTC, paolo-venturi commented on src/frontend/components/message.js
> +			return html`<div class="message-date">Yesterday</div>`;
Ritronata scritta in inglese

2023-06-22 08:22 UTC, paolo-venturi approved these changes

2023-06-22 08:23 UTC, merged