Restyling editor emoji e locale in italiano
Studiofarma/Infolab pull request #164
Opened 2023-06-21 14:10 UTC by MalgarottiMirko

2023-06-21 14:16 UTC, DavideRichini commented
i colori della ricerca grigio su nero rendono molto difficile la lettura
i nomi delle emoji sono ancora in inglese

2023-06-21 15:04 UTC, DavideRichini approved these changes

2023-06-22 08:47 UTC, DavideRichini approved these changes

2023-06-22 12:25 UTC, paolo-venturi requested changes
La finestra flottante con la selezione emoji dovrebbe chiudersi se si clicca un punto esterno alla floating

2023-06-22 12:25 UTC, paolo-venturi commented on src/frontend/pages/chat/input/input-controls.js
>  import { Picker } from "emoji-picker-element";
import inutile

2023-06-22 12:25 UTC, paolo-venturi commented on src/frontend/pages/chat/input/input-controls.js
> +            .i18n=${it}
approfittiamo della modifica per spostare tutto in un componente dedicato

2023-06-23 09:17 UTC, Guidetti-Daniele approved these changes

2023-06-23 09:25 UTC, paolo-venturi approved these changes

2023-06-23 09:25 UTC, merged