Fe/componente unico ricerca
Studiofarma/Infolab pull request #165
Opened 2023-06-21 14:41 UTC by DavideRichini

2023-06-22 06:47 UTC, MalgarottiMirko approved these changes

2023-06-22 09:44 UTC, MalgarottiMirko commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
>  import { ConversationDto } from "../../../../models/conversation-dto.js";
rimuovi i .js

2023-06-22 09:45 UTC, MalgarottiMirko commented on src/frontend/pages/chat/sidebar/sidebar.js
>  import "./conversation/conversation-list.js";
stessa cosa

2023-06-22 09:47 UTC, MalgarottiMirko commented
![image](https://github.com/Studiofarma/Infolab/assets/100234459/d967a828-c1a6-4294-a405-1ea39898bc49)

2023-06-22 09:49 UTC, MalgarottiMirko approved these changes

2023-06-22 12:00 UTC, paolo-venturi requested changes
il componente va riutilizzato anche nella flottante per la selezione dell'utente a cui fare l'inoltro

2023-06-22 14:56 UTC, Guidetti-Daniele requested changes
Sulla console viene visualizzato, questo errore, prova a risolverlo e a capire di cosa si tratta
![image](https://github.com/Studiofarma/Infolab/assets/104075123/427fedb5-5ef2-4950-b64a-908d66e8dd72)

2023-06-22 14:56 UTC, Guidetti-Daniele commented on src/frontend/components/forward-list.js
> +      !this.checkIfClickIsOuter(e) // controlla se si sta cliccando nel backdrop
Trovato un bug: quando si clicca su un componente qualsiasi dell'il-conversation-list il dialog viene chiuso!
Il dialog dovrebbe chiudersi solo se viene cliccata una conversazione; probabilmente il bug deriva dalla gestione dell'evento.

2023-06-23 09:02 UTC, paolo-venturi requested changes

2023-06-23 09:02 UTC, paolo-venturi commented on src/frontend/components/forward-list.js
> +import "../pages/chat/sidebar/conversation/conversation-list.js";
js nell'import da rimuovere

2023-06-23 09:17 UTC, MalgarottiMirko approved these changes

2023-06-23 09:22 UTC, paolo-venturi commented on src/frontend/components/forward-list.js
> +import "../pages/chat/sidebar/conversation/conversation-list.js";
manca ancora questa correzione

2023-06-23 10:01 UTC, paolo-venturi approved these changes

2023-06-23 10:01 UTC, merged