Migliorato il css generale
Studiofarma/Infolab pull request #17
Opened 2023-01-26 21:18 UTC by MalgarottiMirko

Ho inoltre trovato un estensione per VS Code che aiuta con la gestione dei colori permettendo di creare una palette in cui, facendo doppio click, si può inserire l'HEX, l'RGB ecc. direttamente nel codice.

https://marketplace.visualstudio.com/items?itemName=RoyAction.color-manager

2023-01-27 10:18 UTC, paolo-venturi commented
Ottima l'idea dell'estensione, nei prossimi giorni vedo di definire una palette di colori completa da usare per il progetto così da mandarla a tutti

2023-01-27 13:21 UTC, paolo-venturi requested changes

2023-01-27 13:21 UTC, paolo-venturi commented on src/frontend/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" /> <!-- Link per le icone material di Google -->
il link corretto per le icone è: https://fonts.googleapis.com/icon?family=Material+Icons

2023-01-27 13:21 UTC, paolo-venturi commented on src/frontend/js/chat.js
> +                  <span> CERCA </span>
sarebbe bello mettere l'icona di ricerca

2023-01-27 13:21 UTC, paolo-venturi commented on src/frontend/css/main.css
> +    font-family: "Inter", "Helvetica Neue", Helvetica, Arial, sans-serif;
il font è corretto ma non viene applicato a button e input

2023-01-27 13:21 UTC, paolo-venturi commented on src/frontend/js/login.js
> +            <span @click=${this.setVisibility} class="material-symbols-rounded"> ${this.pswVisibility ? "visibility" : "visibility_off"} </span>
la classe CSS material-symbols-rounded non esiste in questo componente, crearla per applicare il font "Material Icons" per fare in modo che le icone vengano mostrate correttamente.
Attenzione all'operatore ternario: dovrebbe essere il contrario.

2023-01-27 18:41 UTC, MalgarottiMirko commented
Ok, dovrei aver corretto tutti i problemi

2023-01-30 08:38 UTC, paolo-venturi approved these changes

2023-01-30 08:38 UTC, merged