aggiunto campo description per manipolare il nome descrittivo della room
Studiofarma/Infolab pull request #174
Opened 2023-06-22 12:19 UTC by Guidetti-Daniele

2023-06-22 14:49 UTC, DavideRichini commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +      this.chatNameFormatter(this.conversationList[index].roomName);
il chatNameFormatter non serve

2023-06-22 14:52 UTC, DavideRichini commented
funzioni come chatNameFormatter vanno tolte anche in forward lis, chat e conversation. Vanno sotituite dal campo description

2023-06-22 14:53 UTC, DavideRichini requested changes
rimuovere funzioni obsolete e completare implementazione nuovo campo

2023-06-23 09:56 UTC, DavideRichini commented
in conversation list gli avatar sono tornati tutti dello stesso colore

2023-06-23 09:57 UTC, DavideRichini commented
forward list non mostra più la lista delle nuove conversazioni

2023-06-23 09:59 UTC, DavideRichini commented
in conversation viene ancora usato chatNameFormatter

2023-06-23 10:00 UTC, DavideRichini requested changes
fare il merge/rebase con il main e fixare i bug segnalati

2023-06-23 11:32 UTC, DavideRichini commented
non inoltra i messaggi

2023-06-23 11:34 UTC, DavideRichini commented on src/frontend/components/forward-list.js
> +      let conversation = new ConversationDto(pharmacy);
non importi conversationDto

2023-06-23 11:38 UTC, DavideRichini commented on src/frontend/pages/chat/chat.js
> +    console.log(event)
togli i console.log

2023-06-27 06:30 UTC, MalgarottiMirko commented on src/frontend/pages/chat/sidebar/sidebar.js
> +          @onChangeConversation=${(event) =>
Il nome dell'evento non segue lo stile degli altri

2023-06-27 06:32 UTC, MalgarottiMirko commented
Rimuovere i SAVEPOINT

2023-06-27 06:33 UTC, MalgarottiMirko commented
Rinominare message-settings

2023-06-27 06:34 UTC, MalgarottiMirko commented
Già che ci sei rimuovi anche "tolot babel-babylonn, acido venturico"

2023-06-27 07:26 UTC, MalgarottiMirko approved these changes

2023-06-27 09:05 UTC, MalgarottiMirko requested changes

2023-06-27 09:05 UTC, MalgarottiMirko commented on src/frontend/pages/chat/chat.js
> +import { ConversationDto } from "../../models/conversation-dto";
import inutile

2023-06-27 12:26 UTC, MalgarottiMirko approved these changes

2023-06-27 12:33 UTC, paolo-venturi commented on src/frontend/components/modal.js
> +export class Modal extends LitElement {
manca una riga vuota per spezzare gli input dalla classe

2023-06-27 12:37 UTC, paolo-venturi commented on src/frontend/components/modal.js
> +    if (changed.has("isOpened") && !this.isOpened) dialog.close();
da riscrivere meglio

2023-06-27 12:38 UTC, paolo-venturi commented on src/frontend/components/modal.js
> +    let dialog = this.renderRoot.querySelector("dialog");
da usare la direttiva ref

2023-06-27 12:39 UTC, paolo-venturi commented on src/frontend/components/popover.js
> +export class Popover extends LitElement {
popover e modal sono molto simili, si possono mettere a fattor comune

2023-06-27 12:40 UTC, paolo-venturi commented on src/frontend/pages/chat/message/message.js
> +            : { top: "0px", right: "-33px" }}
magic string

2023-06-27 12:41 UTC, paolo-venturi commented on src/frontend/pages/chat/message/message-options.js
> +    let chatElement = document
usare la direttiva ref e ricevere l'elemento

2023-06-27 12:46 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +                      width: "400px",
esporre tutte le proprietà css non mi sembra molto gestibile: meglio definire una classe in modal selezionabile da fuori

2023-06-27 12:47 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +    let modal = this.renderRoot.querySelector("il-modal");
rimuovere i query selector: usare la direttiva ref

2023-06-27 12:50 UTC, paolo-venturi requested changes
c'è anche un bug grafico: se si apre il menu dei messaggi ed il messaggio è in basso (l'ultimo vicino all'editor) si sposta in alto

2023-06-28 09:16 UTC, MalgarottiMirko commented
La forward list non si chiude quando si clicca all'esterno

2023-06-28 09:19 UTC, MalgarottiMirko requested changes

2023-06-28 09:19 UTC, MalgarottiMirko commented on src/frontend/components/input-ricerca.js
> +    this.isFocus = this.isFocus == true && this.value != "";
rimuovi == true

2023-06-28 09:31 UTC, MalgarottiMirko approved these changes

2023-06-28 09:50 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +          this.activeDescription != "Generale"
Generale è una descrizione: non va usata per le condizioni, meglio usare name che è un nome tecnico

2023-06-28 13:36 UTC, paolo-venturi approved these changes

2023-06-28 13:36 UTC, merged