Rework editor
Studiofarma/Infolab pull request #175
Opened 2023-06-23 08:19 UTC by MalgarottiMirko

2023-06-23 08:48 UTC, DavideRichini commented
gli elenchi vengono applicati solo alla prima riga e se il testo non è selezionato vengono inseriti a fine linea

2023-06-23 08:49 UTC, DavideRichini commented
quando si inserisce il markdown dall'editor l'inputfield perde il focus

2023-06-23 08:50 UTC, DavideRichini commented
se si va a capo dopo un title viene visualizzato un \

2023-06-23 08:59 UTC, DavideRichini commented
non si apre più il selettore emoji

2023-06-23 09:04 UTC, DavideRichini commented
se si usa una shortcut del browser che include alt (esempio alt+d) viene applicato il markdown quando si premono s, l, i e b e viene poi inserita la lettera

2023-06-23 09:09 UTC, DavideRichini requested changes
applicare i fix richiesti

2023-06-23 14:32 UTC, MalgarottiMirko commented
> gli elenchi vengono applicati solo alla prima riga e se il testo non è selezionato vengono inseriti a fine linea

L modifiche al markdown le faccio in una storia a parte

2023-06-23 15:06 UTC, DavideRichini commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    editor?.focus();
non si puo reggiungere questo codice senza l'editor caricato

2023-06-23 15:23 UTC, DavideRichini commented on src/frontend/pages/chat/input/emoji-picker.js
>        --outline-color: black;
il css per l'emoji picker non serve

2023-06-23 15:23 UTC, DavideRichini commented on src/frontend/pages/chat/input/editor/editor.js
> +    openPreview: { type: Boolean },
variabile non usata

2023-06-23 15:24 UTC, DavideRichini commented on src/frontend/pages/chat/input/editor/editor.js
> +    this.lastKeyPressed = "";
come sopra

2023-06-23 15:25 UTC, DavideRichini commented on src/frontend/pages/chat/input/editor/editor.js
> +      font-family: "Inter", "Helvetica Neue", Helvetica, Arial, sans-serif;
basta inherit

2023-06-23 15:27 UTC, DavideRichini commented on src/frontend/pages/chat/input/editor/editor.js
> +    }
non serve

2023-06-23 15:33 UTC, DavideRichini commented on src/frontend/pages/chat/input/editor/editor.js
> +    if (event.key == "Alt") this.altPressed = false;
le variabili non vengono mai usate

2023-06-23 15:44 UTC, DavideRichini requested changes
fare le modifiche richieste

2023-06-26 06:39 UTC, DavideRichini commented on src/frontend/pages/chat/input/emoji-picker.js
>      }
questo css non serve

2023-06-26 06:42 UTC, DavideRichini requested changes
quando si va a capo l'editor non va in fondo

2023-06-26 07:19 UTC, DavideRichini approved these changes

2023-06-26 07:32 UTC, paolo-venturi commented on src/frontend/components/message-settings.js
> +            this.copyToClipboard(this.message.content.replaceAll("\\\n", "\n"))}
la replace sarebbe meglio metterla in una funzione apposita che ne isola il comportamento
valutare poi se ha senso richiamarla dentro copyToClipboard

2023-06-26 07:37 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +    textarea.style.height = "21px";
magic string

2023-06-26 07:38 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +    const scrollHeight = textarea.scrollHeight;
costante inutile, si può usare direttamente il valore nella riga sotto

2023-06-26 08:19 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +    if (event.key == "Enter") {
magic string

2023-06-26 08:24 UTC, paolo-venturi commented on src/frontend/pages/chat/input/input-controls.js
> +    emojiPicker.style.bottom = `${event.detail.height + 90}px`;
90 valore da costante

2023-06-26 08:27 UTC, paolo-venturi commented on src/frontend/pages/chat/input/insertion-bar.js
> +          ${this.bEditor
si potrebbe usare when?

2023-06-26 08:32 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +    messageBox.style.height = `calc(100vh - ${event.detail.height + 150}px)`;
100vh valore da costante

2023-06-26 08:35 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +    this.message = e.detail.message.replaceAll("\\\n", "\n");
logica aggiunta alla funzione poco leggibile

si può dividere in più funzioni?
ha senso creare un servizio apposito o metterla in un servizio esistente?
alcune logiche sono duplicate nel repository?

2023-06-26 08:39 UTC, paolo-venturi commented on src/frontend/services/markdown-service.js
> +  static getEditor() {
che un servizio possa accedere alla pagina per recuperare un elemento renderizzato non mi convince

riesci a trovare una soluzione migliore?

2023-06-26 08:40 UTC, paolo-venturi commented on src/frontend/services/markdown-service.js
> +    const editor = MarkdownService.getEditor();
c'è tantissima duplicazione di codice in questo servizio
prova a rimuoverla e prova a pensare se tutta la logica inserita qui è corretto che sia qui

2023-06-26 08:42 UTC, paolo-venturi requested changes
altre 2 cose:
- l'indentazione verticale va bene ra una funzione e l'altra, dentro le funzioni manca ancora
- ogni volta che si digita qualcosa nell'editor la chat si posiziona sull'ultimo messaggio anche se si è posizionati su un messaggio più vecchio

2023-06-26 14:14 UTC, DavideRichini approved these changes

2023-06-27 06:38 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +    if (currentKeyPressed === "b")
c'è un costrutto migliore per sostituire catene di if-else-if
"b", "i", etc sono sempre magic string

2023-06-27 06:41 UTC, paolo-venturi commented on src/frontend/pages/chat/input/input-controls.js
> +            style="bottom: 120px;"
lo style messo direttamente nel tag html non è l'ideale
perché non usare emoji-picker-editor-opened che esiste ma non viene più usata?

2023-06-27 06:45 UTC, paolo-venturi commented on src/frontend/services/markdown-service.js
> +    let regEx = /[*]{2}/g;
alcune funzioni insert si somigliano molto tra loro, cosa conviene fare?

2023-06-27 07:31 UTC, DavideRichini commented on src/frontend/pages/chat/input/input-controls.js
>      }
non si puo aggregare in il-emoji-picker?

2023-06-27 07:34 UTC, DavideRichini commented on src/frontend/services/markdown-service.js
> +  }
funzioni ricorsive senza condizione di uscita

2023-06-27 07:40 UTC, DavideRichini requested changes
se si inizia uno strike dentro un bold/italic e lo si chiude fuori vengono messe le tilde e non il md

2023-06-27 07:41 UTC, MalgarottiMirko commented
Il markdown lo sistemeremo in una storia a parte

2023-06-27 09:04 UTC, McGyv246 approved these changes

2023-06-27 09:12 UTC, paolo-venturi approved these changes

2023-06-27 09:14 UTC, merged