navigazione con freccie del risultato della ricerca
Studiofarma/Infolab pull request #187
Opened 2023-06-23 14:44 UTC by DavideRichini

2023-06-23 14:48 UTC, MalgarottiMirko approved these changes

2023-06-23 14:58 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +  arrowNavigation(e) {
nome della funzione fuorviante

2023-06-23 14:59 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    else if (e.detail.key == "ArrowUp" && this.indexOnConversationList > -1)
"ArrowUp", "ArrowDown", etc.. sono magic string

2023-06-23 14:59 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (e.detail.key == "Enter" && this.indexOnConversationList > -1) {
la funzione fa un sacco di cose diverse, meglio spezzarla

2023-06-26 06:49 UTC, MalgarottiMirko approved these changes

2023-06-26 06:59 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    this.arrowUp = "ArrowUp";
arrowUp e arrowDown sono costanti

2023-06-26 07:02 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (
@DavideRichini @MalgarottiMirko le logiche della funzione restanto complicate e poco leggibili

2023-06-26 07:03 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (e.detail.key == "Enter" && this.indexOnConversationList > -1) {
@DavideRichini, @MalgarottiMirko la funzione fa ancora parecchie cose e poco chiare

2023-06-26 07:04 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +          (conversation.roomName == this.activeChatName ||
codice poco leggibile e duplicato

2023-06-26 07:05 UTC, paolo-venturi requested changes
Oltre alle segnalazione nel codice c'è un problema se si scorre con le frecce ed ho molti risultati la posizione della scrollbar non si aggiorna e la selezione non viene visualizzata

2023-06-26 09:46 UTC, MalgarottiMirko commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (e.detail.key == "Enter" && this.indexOfSelectedChat > -1)
Magic string

2023-06-26 09:51 UTC, MalgarottiMirko approved these changes

2023-06-26 09:58 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +  changeIndexOfSelectedChat(key, maxIndex) {
serve davvero passare maxIndex?

2023-06-26 09:59 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    else if (key == arrowUp && this.indexOfSelectedChat > -1)
this.indexOfSelectedChat > -1 quante volte compare?

2023-06-26 10:00 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (key == arrowDown && this.indexOfSelectedChat < maxIndex)
```suggestion
    if (key == arrowDown && this.indexOfSelectedChat < maxIndex)
        this.indexOfSelectedChat++;
        
    if (key == arrowUp && this.indexOfSelectedChat > -1)
        this.indexOfSelectedChat--;
```

2023-06-26 10:02 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +    if (this.indexOfSelectedChat > -1) {
```suggestion
    if (this.indexOfSelectedChat <= -1) {
        this.selectedRoom = "";
        return;
    }

    let room = this.indexOfSelectedChat < convListLength
        ? this.conversationListFiltered[this.indexOfSelectedChat].roomName
        : this.newConversationListFiltered[
            this.indexOfSelectedChat - convListLength
        ].roomName;
    this.selectedRoom = room;
```

2023-06-26 10:13 UTC, MalgarottiMirko approved these changes

2023-06-26 10:31 UTC, paolo-venturi requested changes
ci sono richieste di modifica non risolte e un bug inserito con gli ultimi commit

2023-06-27 07:12 UTC, paolo-venturi approved these changes

2023-06-27 07:13 UTC, paolo-venturi requested changes
c'è un bug grafico quando si scorre la lista in basso: l'input di ricerca non resta fisso

2023-06-27 09:15 UTC, Guidetti-Daniele approved these changes

2023-06-27 09:17 UTC, Guidetti-Daniele commented
Fare il merge con il main e risolvere i conflitti

2023-06-27 12:59 UTC, paolo-venturi approved these changes

2023-06-27 12:59 UTC, merged