Restyling generale chat
Studiofarma/Infolab pull request #191
Opened 2023-06-27 15:10 UTC by McGyv246

2023-06-27 15:29 UTC, MalgarottiMirko approved these changes

2023-06-28 06:55 UTC, paolo-venturi commented on src/frontend/components/input-ricerca.js
> +      div:focus {
serve?

2023-06-28 06:56 UTC, paolo-venturi commented on src/frontend/components/input-ricerca.js
> +        .style=${this.isFocus
meglio definire una classe CSS per il focus e un'altra senza focus

2023-06-28 06:57 UTC, paolo-venturi commented on src/frontend/components/input-ricerca.js
> +          content=${(this.isFocus && this.value != "") == true ||
condizione da riscrivere meglio

2023-06-28 07:13 UTC, paolo-venturi commented on src/frontend/pages/chat/input/editor/editor.js
> +      new CustomEvent("editor-rendered", {
l'evento editor-rendered non mi convince, non sarebbe meglio esporre dei metodi di "focus editor" dal componente editor e dall'input.controls?

2023-06-28 07:15 UTC, paolo-venturi commented on src/frontend/pages/chat/chat.js
> +    let conversationList = this.shadowRoot
usare ref ed esporre dei metodi appositi

2023-06-28 07:15 UTC, paolo-venturi requested changes
i link risultano non leggibili nei messaggi inviati

2023-06-28 08:37 UTC, MalgarottiMirko approved these changes

2023-06-28 08:47 UTC, MalgarottiMirko approved these changes

2023-06-28 09:47 UTC, MalgarottiMirko approved these changes

2023-06-28 10:34 UTC, paolo-venturi approved these changes

2023-06-28 10:34 UTC, merged