Test per l'header
Studiofarma/Infolab pull request #212
Opened 2023-06-29 15:04 UTC by Guidetti-Daniele

2023-06-29 15:15 UTC, McGyv246 requested changes

2023-06-29 15:15 UTC, McGyv246 commented on src/frontend/cypress/e2e/header.cy.js
> +    cy.litElementExist("il-app,il-chat,il-chat-header");
Visto che il path ai componenti è scritto uguale in più punti magari metti una costante che lo contiene (lo stesso anche per eventuali altre stringhe di duplicazione).
Dove c'è questo path + un altro pezzo aggiungilo con la string interpolation. (Se è utilizzato in un solo punto va bene farla lì, se no crea un'altra costante)

2023-06-29 15:15 UTC, McGyv246 commented on src/frontend/cypress/e2e/header.cy.js
> +  cy.login({ user: "user1", password: "password1" });
Questo puoi metterlo in un beforeEach così non lo devi scrivere tutte le volte.

2023-06-30 06:34 UTC, paolo-venturi approved these changes

2023-06-30 07:02 UTC, merged