Refactoring. Extracted components.
Studiofarma/Infolab pull request #213
Opened 2023-06-29 15:09 UTC by McGyv246

2023-06-29 15:26 UTC, DavideRichini commented on src/frontend/pages/chat/message/message-menu-popup.js
> +export class MessageMenuPopup extends LitElement {
manca indentazione verticale

2023-06-29 15:26 UTC, DavideRichini commented on src/frontend/pages/chat/message/message-content.js
> +    }
non ci sono input

2023-06-29 15:27 UTC, DavideRichini commented on src/frontend/pages/chat/message/message-content.js
> +    .sender::after {
manca indentazione verticale

2023-06-29 15:27 UTC, DavideRichini commented on src/frontend/pages/chat/message/message-content.js
> +    .receiver::after {
come sopra

2023-06-29 15:27 UTC, DavideRichini commented on src/frontend/pages/chat/message/message-content.js
> +    .receiver-name {
come sopra

2023-06-29 15:28 UTC, DavideRichini requested changes
sistemare

2023-06-30 09:35 UTC, DavideRichini approved these changes

2023-06-30 13:34 UTC, paolo-venturi approved these changes

2023-06-30 13:34 UTC, merged