inoltro di un messaggio a più chat
Studiofarma/Infolab pull request #218
Opened 2023-06-30 14:21 UTC by DavideRichini

2023-06-30 14:46 UTC, Guidetti-Daniele requested changes

2023-06-30 14:46 UTC, Guidetti-Daniele commented on src/frontend/components/button-text.js
> +      isDisadled: false,
Se non viene usata, togliere questa proprietà, altrimenti sistemare il nome

2023-06-30 14:54 UTC, Guidetti-Daniele approved these changes

2023-07-03 07:32 UTC, Guidetti-Daniele commented
Fix per la lista di inoltro:

1). Se si clicca sopra una conversazione, e non sul suo checkbox, allora il messaggio selezionato viene inviato direttamente al singolo contatto
senza permettere di selezionarne altri. Il comportamento che suggerirei di implementare sarebbe il seguente: quando viene cliccato (indipendentemente dal punto in cui viene fatto il click) un contatto allora
il checkbox di tale contatto viene contrassegnato con il flag. 

2). Quando si inoltra un messaggio attraverso la nuova funzionalità, le chat dei destinatari vengono scalate in cima alla lista (come è giusto che sia), però si rimane nella chat da cui il messaggio viene inoltrato.
Per esempio se invio un messaggio da "Generale" a Davide" e Lorenzo" bisognerebbe far sì che venga caricata la chat di "Lorenzo" a termine inoltro poichè è l'ultima chat a cui è stato inoltrato il messaggio.
Secondariamente quando si inoltra a più chat, le conversazioni nella sidebar devono essere scalate con lo stesso ordine con cui sono state selezionate nel modal.

3). Basandosi sulle correzioni proposte nel punto 2, bisognerebbe applicarle anche qualora si invii un messaggio a delle nuove conversazioni.

4). fix grafico: quando viene aperta l'interfaccia per l'inoltro, il tasto "Inoltra" non è visibile fintanto che l'utente non seleziona una conversazione; sarebbe meglio che quando viene aperto il modal
 il tasto sia visibile ma disabilitato, applicandogli un colore di sfondo grigio.

5). Trovato bug: non sempre tutte le volte che il tasto inoltra viene cliccato funziona! Qualche volta capita , cambiando chat, che il tasto inoltra smetta di funzionare inaspettatamente anche se successivamente si ci sposta su altre
conversazioni.
Trovare la fonte del bug e risolverlo.

2023-07-03 09:51 UTC, Guidetti-Daniele commented
Il bug del punto 5 è stato inserito in proposal

2023-07-03 10:21 UTC, Guidetti-Daniele commented
Dal punto di vista delle funzionalità mi sembra ok

2023-07-03 10:21 UTC, Guidetti-Daniele approved these changes

2023-07-03 10:52 UTC, Guidetti-Daniele approved these changes

2023-07-03 13:19 UTC, paolo-venturi approved these changes

2023-07-03 13:19 UTC, merged