Tooltip
Studiofarma/Infolab pull request #232
Opened 2023-07-03 15:36 UTC by McGyv246

2023-07-03 15:49 UTC, Guidetti-Daniele requested changes

2023-07-03 15:49 UTC, Guidetti-Daniele commented on src/frontend/components/button-icon-with-tooltip.js
> +      ${this.tooltipText && (this.condition === undefined || this.condition)
Utilizzare la feature when come indicato nelle good practices al posto dell'operatore ternario

2023-07-04 06:56 UTC, Guidetti-Daniele approved these changes

2023-07-04 07:10 UTC, paolo-venturi requested changes
Non c'è bisogno di creare un nuovo componente per i pulsanti con Tooltip, la funzionalità sarebbe meglio aggiungerla al componente ButtonIcon

2023-07-04 08:19 UTC, Guidetti-Daniele approved these changes

2023-07-04 08:21 UTC, paolo-venturi approved these changes

2023-07-04 08:22 UTC, merged