Fatti test per messaggi
Studiofarma/Infolab pull request #244
Opened 2023-07-04 14:03 UTC by Guidetti-Daniele

2023-07-04 14:21 UTC, MalgarottiMirko requested changes
Inoltre il terzo test mi da errore

2023-07-04 14:21 UTC, MalgarottiMirko commented on src/frontend/cypress/e2e/messages.cy.js
> +const SIDEBAR_CONVERSATION_LIST =
Il case delle costanti non va bene

2023-07-04 14:21 UTC, MalgarottiMirko commented on src/frontend/package.json
> +    "cypress-real-events": "^1.8.1",
rimuovilo dal momento che non viene utilizzato

2023-07-04 15:12 UTC, MalgarottiMirko approved these changes

2023-07-05 09:56 UTC, MalgarottiMirko approved these changes

2023-07-05 13:54 UTC, McGyv246 approved these changes
I test passano tutti. L'ho testata anche a mano va tutto bene.

2023-07-05 14:45 UTC, paolo-venturi approved these changes

2023-07-05 14:45 UTC, merged