Message edit
Studiofarma/Infolab pull request #246
Opened 2023-07-04 15:09 UTC by McGyv246

Implementazione complete editing dei messaggi (solo in locale)

2023-07-04 15:19 UTC, Guidetti-Daniele requested changes

2023-07-04 15:19 UTC, Guidetti-Daniele commented on src/frontend/pages/chat/chat.js
> +                      this.editMessage(event);
Puoi riscriverlo semplicemente come @edit-message=${this.editMessage}, l'evento viene passato di default

2023-07-04 15:19 UTC, Guidetti-Daniele commented on src/frontend/pages/chat/input/input-controls.js
> +    messageBeingEdited: {},
Manca il campo type

2023-07-04 15:21 UTC, Guidetti-Daniele approved these changes

2023-07-05 06:47 UTC, paolo-venturi approved these changes

2023-07-05 06:48 UTC, merged