Fe/user status
Studiofarma/Infolab pull request #249
Opened 2023-07-05 09:52 UTC by McGyv246

2023-07-05 09:58 UTC, Guidetti-Daniele requested changes

2023-07-05 09:58 UTC, Guidetti-Daniele commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +      console.log(this.usersList);
togliere il console.log

2023-07-05 10:07 UTC, Guidetti-Daniele approved these changes

2023-07-05 11:58 UTC, paolo-venturi commented on src/frontend/components/avatar.js
> +      color: #007928;
Cambiare con #68C47E

2023-07-05 11:58 UTC, paolo-venturi commented on src/frontend/components/avatar.js
> +      color: #6f7174;
Cambiare con #DBDDE0

2023-07-05 11:59 UTC, paolo-venturi requested changes
Aggiungere l'indicazione anche nell'header (solo nella chat singola selezionata)

2023-07-06 07:04 UTC, Guidetti-Daniele approved these changes

2023-07-06 08:16 UTC, paolo-venturi approved these changes

2023-07-06 08:16 UTC, merged