aggiornamento messaggi non letti live
Studiofarma/Infolab pull request #296
Opened 2023-07-23 13:06 UTC by Guidetti-Daniele

Note:
* Non so bene se ho fatto l'implementazione correttamente, fatemi sapere se ho sbagliato a impostare la issue #37.
* Nelle 2 funzione che ho creato per settare/unsettare  il contatore dei messaggi non letti faccio ricorso alla funzione findIndex() sulla conversationList; questo pezzo di codice viene usato più volte anche in altre funzioni, sarebbe meglio implementare una funzione apposita che abbia come parametro la chiave da ricercare nell'array e restituisca l'indice

2023-07-24 09:21 UTC, paolo-venturi requested changes
eseguire il refactoring relativo alla ricerca degli elementi nelle liste da aggiornare

2023-07-25 16:56 UTC, Guidetti-Daniele commented
Ho rivalutato la mia idea iniziale di fare una funzione che restituisse un indice, alla fine sarebbe uscita una modifica molto simile al sistema precedente. Quindi ho preferito implementare un altro tipo di funzione che permetta di accedere a una conversazione nei 2 array con la funzione findConversationByRoomName(roomName)...

2023-07-26 06:47 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +  findConversationByRoomName(roomName) {
funzione da rifattorizzare, scritta così risulta poco leggibile

2023-07-26 06:48 UTC, paolo-venturi requested changes
refactoring funzione

2023-07-27 09:20 UTC, paolo-venturi requested changes
il problema non è il nome della funzione ma come è scritta, è poco leggibile perché:
- è difficile capire facilmente che la funzione opera su 2 liste diverse
- ci sono troppe if innestate per la complessità dell'algoritmo
- viene cercato l'indice invece di recuperare direttamente l'elemento corretto

2023-07-28 06:58 UTC, paolo-venturi requested changes
Non ci siamo, aggiungere complessità computazionale unendo gli array non migliora la leggibilità.
Spezza la funzione:
- una funzione cerca tutte le conversazioni
- una funzione richiamata dalla prima cerca nelle conversazioni aperte
- una funzione richiamata dalla prima cerca nelle conversazioni nuove
- le funzioni usano una find invece di una findIndex

2023-07-31 06:54 UTC, paolo-venturi requested changes
Ora va quasi bene, unico problema: verrebbe fatta una ricerca su entrambe le liste anche se la room fosse presente nella openConversationList.
Evitiamo elaborazioni inutili...

2023-07-31 10:22 UTC, paolo-venturi approved these changes

2023-07-31 10:23 UTC, merged