Cambio logica per chat private / di gruppo
Studiofarma/Infolab pull request #300
Opened 2023-07-29 15:05 UTC by Guidetti-Daniele

Note:
Ho implementato il campo roomType fornito dall'API rooms dal BE, tuttavia vorrei chiedere alcune cose:

* Il campo visibility fornito dalla stessa API come deve essere implementato nel FE?
* Si potrebbe togliere il campo lastDescription nel cookie: quando si entra nell'app viene aperta l'ultima chat lasciata aperta tramite una logica posta nel componente conversation-list che utilizza il campo lastChat contenuto nel cookie, dopodichè viene passata la conversazione intera con tutti i suoi campi. Pertanto in chat si potrebbero rimpiazzare i campi activeDescription e roomType (aggiunto in questa PR), con un campo activeConversation che contenga queste informazioni

2023-07-31 06:58 UTC, paolo-venturi commented on src/frontend/pages/chat/sidebar/conversation/conversation-list.js
> +      visibility: "PRIVATE",
-magic strings
-c'è un modo migliore di gestire il valore di default

2023-07-31 07:01 UTC, paolo-venturi requested changes
piccole sistemazioni

2023-07-31 07:03 UTC, paolo-venturi commented
> Note: Ho implementato il campo roomType fornito dall'API rooms dal BE, tuttavia vorrei chiedere alcune cose:
> 
> * Il campo visibility fornito dalla stessa API come deve essere implementato nel FE?
> * Si potrebbe togliere il campo lastDescription nel cookie: quando si entra nell'app viene aperta l'ultima chat lasciata aperta tramite una logica posta nel componente conversation-list che utilizza il campo lastChat contenuto nel cookie, dopodichè viene passata la conversazione intera con tutti i suoi campi. Pertanto in chat si potrebbero rimpiazzare i campi activeDescription e roomType (aggiunto in questa PR), con un campo activeConversation che contenga queste informazioni

- Il campo visibility al momento va aggiunto al DTO ma non utilizzato.
- Ok per activeConversation

2023-08-01 08:27 UTC, paolo-venturi commented
conflitti da risolvere e nuova gestione API del backend da integrare

2023-08-01 09:48 UTC, Guidetti-Daniele commented
Mergiato

2023-08-02 08:02 UTC, paolo-venturi requested changes
Test di selezione conversazione rossi

2023-08-05 20:55 UTC, Guidetti-Daniele commented
Riguardo l'ultimo commit  ho pensato che fosse meglio refactorizzare il file open-chat.cy.js e allora ho deciso di riscrivere questi test seguendo  i punti che ho propost nella issue #315

2023-08-07 06:44 UTC, paolo-venturi commented
> Riguardo l'ultimo commit ho pensato che fosse meglio refactorizzare il file open-chat.cy.js e allora ho deciso di riscrivere questi test seguendo i punti che ho propost nella issue #315

La proposta è valida.
C'è però un problema nel flusso di lavoro che stai utilizzando: non puoi fare una proposta di modifica articolandola su una issue e poi svilupparla senza attendere l'approvazione su un ramo relativo ad un'altra issue.
Nel caso in cui la proposta non andasse bene dovresti rimuovere il commit e il reviewer dovrebbe ricontrollare tutto dall'inizio.
Nel caso (quello attuale) in cui la proposta va bene il reviewer deve controllare 2 diverse implementazioni in un solo ramo e cancellare la nuova issue (#315) non più necessaria.

2023-08-07 08:30 UTC, paolo-venturi commented
I test non funzionano

2023-08-11 13:46 UTC, Guidetti-Daniele commented
> I test non funzionano

Ok, mi scuso davvero per l'inattività, questa PR dovevo terminarla già settimana scorsa, e adesso ho bisogno di qualche consiglio:

- Ho appena mergiato il main attuale nel mio ramo e ho risolto i conflitti; aprendo l'app ottengo la progress bar che gira, e le conversazioni non vengono mai caricate. Anche sul main mi succede questo, quindi suppongo che sia il comportamento corretto.

- Riguardo i test oggi mentre stavo guardando ho riscontrato questo problema: ho verificato che tutti i test vanno quando li eseguo con il cypress:open , tuttavia quando uso il cypress:run la maggior parte di questi mi falliscono. (vedere img)

![image](https://github.com/Studiofarma/Infolab/assets/104075123/2e9bdd04-5fe2-44a7-8d26-b09349e02fdb)

Tali test falliscono sempre con il beforeEach, dandomi il seguente errore (vedere img) :

![errore beforeEach](https://github.com/Studiofarma/Infolab/assets/104075123/10608d17-be4c-4b6c-9ff5-456e7ee78034)

Tuttavia non ho capito a cosa sia dovuto e tale problema è presente anche nel main.
Pertanto volevo chiedere un'opinione su come proseguire riguardo i test.

2023-08-11 15:11 UTC, paolo-venturi commented
> > I test non funzionano
> 
> Ok, mi scuso davvero per l'inattività, questa PR dovevo terminarla già settimana scorsa, e adesso ho bisogno di qualche consiglio:
> 
> * Ho appena mergiato il main attuale nel mio ramo e ho risolto i conflitti; aprendo l'app ottengo la progress bar che gira, e le conversazioni non vengono mai caricate. Anche sul main mi succede questo, quindi suppongo che sia il comportamento corretto.
> * Riguardo i test oggi mentre stavo guardando ho riscontrato questo problema: ho verificato che tutti i test vanno quando li eseguo con il cypress:open , tuttavia quando uso il cypress:run la maggior parte di questi mi falliscono. (vedere img)
> 
> ![image](https://user-images.githubusercontent.com/104075123/260022712-2e9bdd04-5fe2-44a7-8d26-b09349e02fdb.png)
> 
> Tali test falliscono sempre con il beforeEach, dandomi il seguente errore (vedere img) :
> 
> ![errore beforeEach](https://user-images.githubusercontent.com/104075123/260022950-10608d17-be4c-4b6c-9ff5-456e7ee78034.PNG)
> 
> Tuttavia non ho capito a cosa sia dovuto e tale problema è presente anche nel main. Pertanto volevo chiedere un'opinione su come proseguire riguardo i test.

Ho lanciato più volte i test ed ora funzionano. Probabilmente i problemi sono dati dal tuo PC personale.
Attendiamo di agganciare i test di cypress alla pipeline prima di investigare ulteriormente.

2023-08-11 15:12 UTC, paolo-venturi approved these changes

2023-08-11 15:12 UTC, merged