Be/custom jwt
Studiofarma/Infolab pull request #372
Opened 2023-09-12 14:07 UTC by McGyv246

Implemented support for jwt token authentication on backend.
Frontend adapted to work as it did before (it does not use jwt).

Closing #366

2023-09-14 15:55 UTC, lucapiccinelli requested changes

2023-09-14 15:55 UTC, lucapiccinelli commented on src/test/java/com/cgm/infolab/LastDownloadDateUpdateTests.java
> +        Thread.sleep(100);
questi li hai aggiunti a causa dell'uso del token? o questi test fallivano ogni tanto e così non falliscono più?

2023-09-14 15:55 UTC, lucapiccinelli commented on src/test/java/com/cgm/infolab/helper/TestStompHelper.java
> +//        StompSession session = websocket
rimuovi le linee commentate

2023-09-14 15:55 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/UsernameSubClaimAdapter.java
> +        String username = (String) convertedClaims.get("user_name");
Che ne dici di fare una classe `JwtConstants` e mettere li queste stringhe? `user_name` e `sub`

2023-09-14 15:55 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/RunAfterStartup.java
> +                    "URL to login as lorenzo through jwt: http://localhost:%d/?access_token=%s"
`http://localhost:%d/?access_token=%s` avento risolto il passaggio del jwt con la modifica a wgbrowser, stamperei solo il token e togliere localhost etc

2023-09-14 15:55 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/RunAfterStartup.java
> +                            .formatted(port, new TestJwtHelper().generateToken("infolab", "lorenzo").getTokenValue()));
in `generateToken` ci mettiamo un'opzione in più per aumentare il tempo di scadenza? qui metterei più di un minuto... aumenterei almeno a un'ora ma anche di più. Fai un overload del metodo e metti il tempo come parametro opzionale, di modo che per i test lasciamo un valore di default

2023-09-14 15:55 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/IsDevOrTestCondition.java
> +        return profiles.contains("dev") || profiles.contains("test");
`dev` e `test` ci facciamo delle costanti? sono usati un po' in tanti posti adesso

2023-09-14 15:55 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/helper/TestJwtHelper.java
> +                .expiresAt(Instant.now().plusMillis(0))
Abbiamo dimenticato `plusMillis(0)`. Come valore di default di metteri 1 minuto

2023-09-15 07:23 UTC, McGyv246 commented on src/test/java/com/cgm/infolab/LastDownloadDateUpdateTests.java
> +        Thread.sleep(100);
La seconda

2023-09-15 10:28 UTC, lucapiccinelli approved these changes

2023-09-15 12:14 UTC, merged