fatto componente snackbar
Studiofarma/Infolab pull request #65
Opened 2023-02-23 16:09 UTC by Guidetti-Daniele

2023-02-24 15:42 UTC, paolo-venturi requested changes

2023-02-24 15:42 UTC, paolo-venturi commented on src/frontend/pages/login/snackbar.js
> +      border-bottom: 5px solid #cf173a;
ok l'idea del colore ma se volessi emettere una info il rosso non andrebbe bene: il colore deve essere parametrico

2023-02-24 15:42 UTC, paolo-venturi commented on src/frontend/pages/login/snackbar.js
> +        <p>CREDENZIALI NON VALIDE</p>
la scritta non deve essere fissa ma passata dall'esterno per poter riutilizzare il componente in altri punti

2023-02-24 15:45 UTC, paolo-venturi commented on src/frontend/pages/login/snackbar.js
> +          content="close"
sistemare l'icona con i nuovi standar

2023-02-26 13:15 UTC, Guidetti-Daniele commented on src/frontend/pages/login/snackbar.js
> +          content="close"
Scusa, non riesco a capire cosa si intenda per "nuovi standard", è forse il componente sbagliato?

2023-02-26 13:24 UTC, Guidetti-Daniele commented on src/frontend/pages/login/snackbar.js
> +          content="close"
Ok no scherzavo, ho visto il nuovo standard

2023-02-27 08:20 UTC, paolo-venturi commented on src/frontend/pages/login/snackbar.js
> +      border-bottom: 5px solid #cf173a;
spiego meglio
con parametrico intendo che andrebbero definite 3 tipologie di snackbar:

1. errore: colore rosso
2. warning: colore giallo
3. info: colore blu

la tipologia viene passata come parametro al componente

2023-02-27 20:11 UTC, Guidetti-Daniele commented on src/frontend/pages/login/snackbar.js
> +      border-bottom: 5px solid #cf173a;
Reso parametrico

2023-03-01 07:52 UTC, paolo-venturi approved these changes

2023-03-01 07:53 UTC, merged