Be/api nuova room
Studiofarma/Infolab pull request #88
Opened 2023-03-15 16:07 UTC by McGyv246

POST api per la creazione di una nuova room.

2023-03-15 16:08 UTC, McGyv246 commented
Nota: così l'api permette la creazione di stanze di 1 utente (basta loggarsi con un utente e mettere nell'url lo stesso.

2023-03-16 15:42 UTC, lucapiccinelli requested changes

2023-03-16 15:42 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/service/RoomService.java
> +            return RoomEntity.of(roomId, roomName, "PRIVATE");
rimuovere magicString `PRIVATE`

2023-03-20 15:40 UTC, lucapiccinelli commented on src/main/java/com/cgm/infolab/service/RoomService.java
> +        String roomName = String.format("%s-%s", users[0], users[1]);
Si. L'obiettivo è avere normalizzazione dello username. Quindi ti puoi rispondere chiedendoti: "in questo punto, una differenza di lowercase o uppercase potrebbe causare un bug". Se la risposta è si, ci metti la classe Username e risolvi il problema

2023-03-21 09:03 UTC, lucapiccinelli approved these changes

2023-03-21 09:04 UTC, merged